ignore:
  # TEMP: glob is fixed to 10.5.0 in package.json/package-lock.json, but DLC may cache old layer
  # Verify fix by running: npm ls glob (should show 10.5.0)
  # Remove this ignore after verifying CI builds fresh image
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
    reason: "glob upgraded to 10.5.0 in package.json - CI DLC may cache stale image layer"
  - vulnerability: CVE-2025-46394
    reason: "No fixes to busybox apk available as of 2025-10-16 on Dockerfile base image 22.20.0-alpine3.22"
  - vulnerability: CVE-2024-58251
    reason: "No fixes to busybox apk available as of 2025-10-16 on Dockerfile base image 22.20.0-alpine3.22"
  - vulnerability: CVE-2025-56200
    include-aliases: true
    reason: "No fixes available as of 2025-10-16 on validator npm package"
  - vulnerability: CVE-2025-60876
    reason: "No fixes available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
