version: "3.7"

services:
  simulator:
    build:
      context: .
    container_name: simulator
    ports:
      - "1080:1080"
    environment:
      - LOG_LEVEL=info
      - TRANSFERS_ENDPOINT=http://172.17.0.1:3000
      - TRANSFERS_FULFIL_RESPONSE_DISABLED=false
      - QUOTES_ENDPOINT=http://172.17.0.1:3002
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:1080/health"]
      timeout: 20s
      retries: 10
      interval: 30s
